spring:
  datasource:
    url: jdbc:postgres:BAecFEC-D4CF3FG-6-gc*g6Ca*CBD1BD@roundhouse.proxy.rlwy.net:45332/railway
    username: postgres
    password: BAecFEC-D4CF3FG-6-gc*g6Ca*CBD1BD

#  jpa:
#    hibernate:
#      ddl-auto: validate

server:
  error:
    include-message: always
    include-binding-error: always
  forward-headers-strategy: framework
  servlet:
    context-path: /

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
